runtime: python313
entrypoint: gunicorn -b :$PORT --timeout 60 config.wsgi:application

handlers:
  - url: /static
    static_dir: staticfiles
  - url: /.*
    script: auto

automatic_scaling:
  max_instances: 2
