runtime: python313
entrypoint: gunicorn -b :$PORT config.wsgi:application

handlers:
  - url: /static
    static_dir: staticfiles
  - url: /.*
    script: auto

vpc_access_connector:
  name: projects/shopify-accountancy/locations/europe-west1/connectors/ext-api

automatic_scaling:
  max_instances: 2
