[project]
name = "shopify-accountancy-api"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0.5",
    "django-guardian>=3.3.1",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt>=5.5.1",
    "drf-spectacular>=0.29.0",
    "psycopg[binary]>=3.3.4",
    "python-decouple>=3.8",
    "shopifyapi>=12.7.0",
]

[dependency-groups]
dev = [
    "django-stubs>=6.0.5",
    "django-types>=0.24.0",
    "djangorestframework-stubs>=3.17.0",
    "pre-commit>=4.6.0",
    "ruff>=0.15.15",
    "ty>=0.0.40",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.ty.src]
include = ["."]
