# Generated by Django 6.0.5 on 2026-05-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("shop_domain", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("access_token", models.CharField(max_length=255)),
                ("scopes", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "permissions": [("can_manage", "Can manage store")],
            },
        ),
    ]
