# Generated by Django 6.0.5 on 2026-06-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_product_productvariant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="suppliers", to="core.store"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_number", models.CharField(blank=True, max_length=255)),
                ("order_date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_raw_material", models.BooleanField(default=False)),
                ("reception_date", models.DateField(blank=True, null=True)),
                ("reception_checked", models.BooleanField(default=False)),
                ("has_supporting_documents", models.BooleanField(default=False)),
                ("claim_text", models.TextField(blank=True, null=True)),
                ("claim_date", models.DateField(blank=True, null=True)),
                ("supplier_return_text", models.TextField(blank=True, null=True)),
                ("claim_closed_at", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="purchases", to="core.store"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="purchases", to="core.supplier"
                    ),
                ),
            ],
        ),
    ]
