# Generated by Django 6.0.5 on 2026-06-13 12:31

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_supplier_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="bank_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
        ),
        migrations.AddField(
            model_name="store",
            name="cash_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("processed_at", models.DateTimeField()),
                ("payment_method", models.CharField(blank=True, max_length=255)),
                ("currency_code", models.CharField(blank=True, max_length=10)),
                ("subtotal_price", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("total_discounts", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("total_price", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("cash_paid_amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("product_purchase_cost", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("net_margin", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("after_tax_result", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("quarter", models.CharField(blank=True, max_length=7)),
                ("shopify_transfer_amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="orders", to="core.store"
                    ),
                ),
            ],
            options={
                "unique_together": {("store", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="OrderDiscount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("SHOPIFY_DISCOUNT", "Shopify discount"), ("STORE_CREDIT", "Store credit")],
                        max_length=20,
                    ),
                ),
                ("external_index", models.IntegerField(blank=True, null=True)),
                ("code", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="discounts", to="core.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderExpense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DELIVERY", "Delivery"),
                            ("PACKAGING", "Packaging"),
                            ("SHOPIFY_PAYMENT", "Shopify payment"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(choices=[("MANUAL", "Manual"), ("AUTO", "Auto")], max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="expenses", to="core.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CashTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ORDER", "Order"),
                            ("ADD_MONEY", "Add Money"),
                            ("WITHDRAW_MONEY", "Withdraw Money"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cash_transactions", to="core.store"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_transactions",
                        to="core.order",
                    ),
                ),
            ],
            options={
                "unique_together": {("store", "order")},
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ORDER", "Order"),
                            ("EMPTY_CASHBOX", "Empty Cashbox"),
                            ("FILL_CASHBOX", "Fill Cashbox"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bank_transactions", to="core.store"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_transactions",
                        to="core.order",
                    ),
                ),
            ],
            options={
                "unique_together": {("store", "order")},
            },
        ),
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("unit_price", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="line_items", to="core.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_line_items",
                        to="core.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_line_items",
                        to="core.productvariant",
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "external_id")},
            },
        ),
    ]
