# Generated by Django 6.0.5 on 2026-06-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_store_bank_amount_store_cash_amount_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("ORDER", "Order"),
                    ("PURCHASE", "Purchase"),
                    ("EMPTY_CASHBOX", "Empty Cashbox"),
                    ("FILL_CASHBOX", "Fill Cashbox"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
