# Generated by Django 6.0.5 on 2026-06-13 17:26

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_banktransaction_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlineitem",
            name="distributor_price",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
        ),
    ]
