# Generated by Django 6.0.5 on 2026-06-15 17:03

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_orderlineitem_distributor_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("ORDER", "Order"),
                    ("PURCHASE", "Purchase"),
                    ("EMPTY_CASHBOX", "Empty Cashbox"),
                    ("FILL_CASHBOX", "Fill Cashbox"),
                    ("TAX", "Tax"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quarter", models.CharField(max_length=7)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bank_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tax",
                        to="core.banktransaction",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="taxes", to="core.store"
                    ),
                ),
            ],
            options={
                "unique_together": {("store", "quarter")},
            },
        ),
    ]
