# Generated by Django 6.0.5 on 2026-06-15 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_banktransaction_source_tax"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tax",
            name="bank_transaction",
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="tax",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transaction",
                to="core.tax",
            ),
        ),
    ]
