# Generated by Django 6.0.5 on 2026-06-19 18:28

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_tax_bank_transaction_banktransaction_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="royalty_rate",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=5),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("ORDER", "Order"),
                    ("PURCHASE", "Purchase"),
                    ("EMPTY_CASHBOX", "Empty Cashbox"),
                    ("FILL_CASHBOX", "Fill Cashbox"),
                    ("TAX", "Tax"),
                    ("ROYALTY", "Royalty"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Royalty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quarter", models.CharField(max_length=7)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="royalties", to="core.store"
                    ),
                ),
            ],
            options={
                "unique_together": {("store", "quarter")},
            },
        ),
        migrations.AddField(
            model_name="banktransaction",
            name="royalty",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transaction",
                to="core.royalty",
            ),
        ),
    ]
