# Generated by Django 6.0.5 on 2026-06-19 19:28

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_royalty"),
    ]

    operations = [
        migrations.AddField(
            model_name="royalty",
            name="sum_after_tax_result",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
        ),
        migrations.AddField(
            model_name="royalty",
            name="sum_purchase_price",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
        ),
    ]
