# Generated by Django 6.0.6 on 2026-07-08 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.constants.profile


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Profile = apps.get_model("core", "Profile")
    Profile.objects.bulk_create([Profile(user=user) for user in User.objects.filter(profile__isnull=True)])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_royalty_breakdown_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "lang",
                    models.CharField(
                        choices=[("en_US", "EN_US"), ("en_GB", "EN_GB"), ("fr_FR", "FR_FR")],
                        default=core.constants.profile.ProfileLang["EN_US"],
                        max_length=5,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_profiles_for_existing_users, migrations.RunPython.noop),
    ]
