# Generated by Django 6.0.6 on 2026-07-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("ORDER", "Order"),
                    ("PURCHASE", "Purchase"),
                    ("EMPTY_CASHBOX", "Empty Cashbox"),
                    ("FILL_CASHBOX", "Fill Cashbox"),
                    ("TAX", "Tax"),
                    ("ROYALTY", "Royalty"),
                    ("ORDER_DELIVERY", "Order Delivery"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
