# Generated by Django 6.0.6 on 2026-07-13 14:16

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def backfill_net_revenue(apps, schema_editor):
    Order = apps.get_model("core", "Order")
    Order.objects.update(net_revenue=F("total_price"))


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_orderlineitem_variant_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="net_revenue",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="returns_purchase_cost",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="total_returns",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
        ),
        migrations.AlterField(
            model_name="banktransaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("ORDER", "Order"),
                    ("PURCHASE", "Purchase"),
                    ("EMPTY_CASHBOX", "Empty Cashbox"),
                    ("FILL_CASHBOX", "Fill Cashbox"),
                    ("TAX", "Tax"),
                    ("ROYALTY", "Royalty"),
                    ("ORDER_DELIVERY", "Order Delivery"),
                    ("RETURN", "Return"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(blank=True, max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="returns",
                        to="core.order",
                    ),
                ),
            ],
            options={
                "unique_together": {("order", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="ReturnLineItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.CharField(max_length=255)),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_line_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_line_items",
                        to="core.orderlineitem",
                    ),
                ),
                (
                    "return_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="core.return",
                    ),
                ),
            ],
            options={
                "unique_together": {("return_ref", "external_id")},
            },
        ),
        migrations.RunPython(backfill_net_revenue, migrations.RunPython.noop),
    ]
