# Generated by Django 6.0.6 on 2026-07-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_order_net_revenue_order_returns_purchase_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="returnlineitem",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
