# Generated by Django 6.0.7 on 2026-07-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_returnlineitem_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="return",
            name="source",
            field=models.CharField(
                choices=[("RETURN", "Return"), ("REFUND", "Refund")], default="RETURN", max_length=10
            ),
        ),
    ]
