# Generated by Django 6.0.7 on 2026-07-28 14:36

from decimal import Decimal

from django.db import migrations
from django.db.models import Sum


def delete_erroneous_order_bank_transactions(apps, schema_editor):
    """Delete BankTransaction(source=ORDER) rows wrongly created for cash-paid orders.

    Before the fix in core/signals/order.py, a BankTransaction was created for every order
    with a shopify_transfer_amount, even when the order was actually paid in cash
    (cash_paid_amount != 0). Those orders should only have a CashTransaction.
    """
    BankTransaction = apps.get_model("core", "BankTransaction")
    Store = apps.get_model("core", "Store")

    erroneous = BankTransaction.objects.filter(source="ORDER").exclude(order__cash_paid_amount=0)
    affected_store_ids = set(erroneous.values_list("store_id", flat=True))
    erroneous.delete()

    for store_id in affected_store_ids:
        bank_amount = BankTransaction.objects.filter(store_id=store_id).aggregate(total=Sum("amount"))[
            "total"
        ] or Decimal("0")
        Store.objects.filter(pk=store_id).update(bank_amount=bank_amount)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_return_source"),
    ]

    operations = [
        migrations.RunPython(delete_erroneous_order_bank_transactions, migrations.RunPython.noop),
    ]
