# Generated by Django 6.0.7 on 2026-08-06 07:43

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_delete_erroneous_order_bank_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="fixed_costs_reserve",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=12),
        ),
    ]
